name: ci
on:
  push:
    branches: [master]
  pull_request:
permissions:
  contents: read
jobs:
  links:
    runs-on: ubuntu-latest
    name: Relative link check
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Check relative Markdown links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: "--offline --no-progress --include-fragments './**/*.md'"
          fail: true
